title: Robert Ogada # your name (or website title) here
logo: "https://media-exp1.licdn.com/dms/image/C4D03AQHd7IWWavL9GA/profile-displayphoto-shrink_800_800/0/1655728319501?e=1671667200&v=beta&t=GNjCdmqxF6TaItcWlvpwPlyAO5mxm-a42XDCUUif7mE" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/robert-ogada-a7173bb1">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-246504655-2 # your Google Analytics tracking ID here
